export { CommandInterface } from "./core/command"
export type { CommandClassMeta, CommandChildMeta, CommandOptionMeta } from "./core/metadata"
export { Command } from "./decorators/command.decorator"
export type { CommandDecoratorOptions } from "./decorators/command.decorator"
export { CommandChild } from "./decorators/child.decorator"
export type { CommandChildDecoratorOptions } from "./decorators/child.decorator"
export { CommandOption } from "./decorators/option.decorator"
export type { CommandOptionDecoratorOptions } from "./decorators/option.decorator"
export { createRuntime, Runtime } from "./runtime/runtime"
export type { RuntimeConfig } from "./runtime/runtime"
export type { CommandResult, CommandError } from "./contracts/command-result"
export type { Middleware } from "./contracts/middleware"

export type { ExecCmdOption, ExecSubCmdOption, NextChildNode } from "./contracts/context"
export type { StandardSchemaV1, StandardTypedV1 } from "./contracts/standard-schema"
export type { CommandMeta, CommandOptionMeta as CommandOptionMetaOut, CommandChildMeta as CommandChildMetaOut } from "./runtime/introspection"
export { DocGenerator } from "./runtime/docgen"
export { CompletionGenerator } from "./runtime/completion"
export { CommandRegistry } from "./runtime/registry"
export { CommandResolver } from "./runtime/resolver"
export type { ParseResult, OptionEntry } from "./runtime/resolver"
export { runCli } from "./adapters/cli/cli-adapter"
export type { CliAdapterOptions } from "./adapters/cli/cli-adapter"
export { handleHttp } from "./adapters/http/http-adapter"
export type { HttpRequest, HttpResponse, HttpAdapterOptions } from "./adapters/http/http-adapter"
export { AIAdapter } from "./adapters/ai/ai-adapter"
export { createMCPServer } from "./adapters/ai/mcp-server"
export { createOpenAIAdapter } from "./adapters/ai/openai"
export type { AITool, AIToolCall, AIToolResult } from "./adapters/ai/types"
